# Copyright 2019 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: asia-northeast1
  SERVICE_NAME: slick-queue
  SLICK_AMQP_URI: ${{ secrets.SLICK_AMQP_URI }}
  SLICK_SCORE_QUEUE_NAME: page-score-requests

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}

    # Set use_kaniko for gcloud build
    - name: UseKaniko
      run: |-
        gcloud config set builds/use_kaniko True
    
    # Set kaniko_cache_ttl for gcloud build
    - name: KanikoCacheTtl
      run: |-
        gcloud config set builds/kaniko_cache_ttl 168

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --timeout "60m" \
          --machine-type=n1-highcpu-8 \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated \
          --memory "128Mi" \
          --set-env-vars "SLICK_AMQP_URI=$SLICK_AMQP_URI,SLICK_SCORE_QUEUE_NAME=$SLICK_SCORE_QUEUE_NAME"
